name: effortsharing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-lock
  - jupyterlab
  - matplotlib
  - pip
  - plotly
  - python=3.12
  - scipy
  - webcolors
  - pip:
      - -e .[dev]  # local library code contained in src/effortsharing with its dependencies in pyproject.toml
