name: effortsharing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-lock  
  - jupyterlab
  - matplotlib
  - pip
  - plotly
  - python=3.11
  - scipy
  - tqdm
  - webcolors
  - pip:
      - -e .[dev]  # local library code contained in src/efforthsharing with its dependencies in pyproject.toml
