name: effortsharing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-lock  
  - jupyterlab
  - matplotlib
  - pip
  - plotly
  - python=3.11
  - scipy
  - tqdm
  - webcolors
  - pip:
      - -e .[dev]  # local library code contained in src/efforthsharing with its dependencies in pyproject.toml


# TODO:
# check if more people need to be added
# consider date versioning
# CITATION.CFF
# Document min version, version, pip vs conda workflow
# Test this shizzle

