name: effortsharing_env
channels:
  - conda-forge
  - defaults
dependencies:
  - conda-lock
  - h5netcdf  # optional dependency of xarray
  - jupyterlab
  - matplotlib
  - netcdf4  # optional dependency of xarray
  - numpy
  - openpyxl  # optional dependency of pandas
  - pandas
  - pip
  - plotly
  - python-kaleido
  - python=3.11
  - pyyaml
  - rich
  - ruff
  - scipy
  - tqdm
  - webcolors
  - xarray
  - pip:
      - SALib  # not available via conda
      - -e .  # local library code contained in src/efforthsharing
