ADDITIONAL_EU_AND_EARTH = {"European Union": "EU", "Earth": "EARTH"}
ADDITIONAL_REGIONS_SSPS = {
    "Aruba": "ABW",
    "Bahamas": "BHS",
    "C?te d'Ivoire": "CIV",
    "Cabo Verde": "CPV",
    "Cura?ao": "CUW",
    "Czechia": "CZE",
    "Democratic Republic of the Congo": "COD",
    "French Guiana": "GUF",
    "French Polynesia": "PYF",
    "Gambia": "GMB",
    "Guadeloupe": "GLP",
    "Guam": "GUM",
    "Hong Kong": "HKG",
    "Iran": "IRN",
    "Macao": "MAC",
    "Martinique": "MTQ",
    "Mayotte": "MYT",
    "Moldova": "MDA",
    "New Caledonia": "NCL",
    "Palestine": "PSE",
    "Puerto Rico": "PRI",
    "R?union": "REU",
    "Syria": "SYR",
    "Taiwan": "TWN",
    "Tanzania": "TZA",
    "Turkey": "TUR",
    "United States Virgin Islands": "VIR",
    "United States": "USA",
    "Venezuela": "VEN",
    "Viet Nam": "VNM",
    "Western Sahara": "ESH",
    "World": "EARTH",
}
